### ISSUE TITLE
make一直失败

### ISSUE THREAD

**Issue by skybbx** [ArtalkJS/Artransfer-CLI#1]
root@MAI-PC:~/Artransfer-CLI# make
go build \
        -ldflags "-s -w -X github.com/ArtalkJS/Artransfer-CLI/lib.Version=v1.0.2 \
        -X github.com/ArtalkJS/Artransfer-CLI/lib.CommitHash=3758ebd" \
        -o bin/artransfer \
        github.com/ArtalkJS/Artransfer-CLI
go: finding github.com/jackc/pgconn v1.8.0
go: finding github.com/jackc/pgproto3/v2 v2.0.6
go: gorm.io/driver/mysql@v1.3.3: unrecognized import path "gorm.io/driver/mysql" (https fetch: Get https://gorm.io/driver/mysql?go-get=1: write tcp 10.10.10.10:5619->185.199.108.153:443: write: connection reset by peer)
go: go.uber.org/tools@v0.0.0-20190618225709-2cfd321de3ee: unrecognized import path "go.uber.org/tools" (https fetch: Get https://go.uber.org/tools?go-get=1: EOF)
go: finding github.com/modocache/gover v0.0.0-20171022184752-b58185e213c5
go: finding golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go: finding golang.org/x/crypto v0.0.0-20201203163018-be400aefbc4c
go: finding golang.org/x/text v0.3.4
go: finding gopkg.in/yaml.v2 v2.2.8
go: finding honnef.co/go/tools v0.0.1-2019.2.3
go: error loading module requirements
make: *** [makefile:8: build] Error 1

其实有没有简单一点的方法，我想将waline上的数据导入，waline导出来的评论数据，官方提供的迁移工具没有waline的选项，我的waline用的是mysql

**Comment by cytvictor** [comment]
> go: gorm.io/driver/mysql@v1.3.3: unrecognized import path "gorm.io/driver/mysql" (https fetch: Get https://gorm.io/driver/mysql?go-get=1: write tcp 10.10.10.10:5619->185.199.108.153:443: write: connection reset by peer)

如果是开发的话，可能由于你那边到 gorm 软件包网络不稳定，试试在 make 前设置一下环境变量 `go env -w GOPROXY=https://goproxy.io,direct` 

> 官方提供的迁移工具没有waline的选项

如果是直接下载[打包好的程序](https://github.com/ArtalkJS/Artransfer-CLI/releases/tag/v1.0.2)使用的话，工具里提供了 waline 且 README 里就有[命令参考](https://github.com/ArtalkJS/Artransfer-CLI#waline)，是我没有理解你的问题吗？
